-- V3: Create stock_events table for audit/event sourcing
-- Idempotent: Uses IF NOT EXISTS

CREATE TABLE IF NOT EXISTS stock_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_item_id VARCHAR(36) NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    event_data TEXT NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_events_stock_item FOREIGN KEY (stock_item_id)
        REFERENCES stock_items(id) ON DELETE CASCADE
);

-- Create index for stock item event queries
CREATE INDEX IF NOT EXISTS idx_stock_events_stock_item_id ON stock_events(stock_item_id);

-- Create index for time-based event queries
CREATE INDEX IF NOT EXISTS idx_stock_events_occurred_at ON stock_events(occurred_at);

-- Create index for event type queries
CREATE INDEX IF NOT EXISTS idx_stock_events_event_type ON stock_events(event_type);
